### ISSUE TITLE
How to change the diameter?

### ISSUE THREAD

**Issue by gangyilisdu** [vedranaa/icosphere#1]

**Comment by javl** [comment]
The following example gives you a variable called `vertices` which contains the positions of all corners of the icosphere, and `faces` which tells you which corners you should connect to form triangles:

    from icosphere import icosphere
    nu = 5  # or any other integer
    vertices, faces = icosphere(nu)

The values of `vertices` are normalized, meaning they are all between `-1` and `1`. For example, the first vertex in the above example has the value `[0.0,    0.52573111,    0.85065081]`, which are its `x`, `y` and `z` positions. Because the maximum distance between the minimum and maximum values is 2 (from -1 to 1) you can multiply any of these values with your `radius` (`diameter / 2`) to get an icosphere at the size you need.

For example: if you want a icosphere of 15 units wide, you multiply each of the the vertex positions with `15 / 2 = 7.5`. So the first vertex which the values `[0.0,    0.52573111,    0.85065081]` should be drawn at `[0.0 * 7.5,    0.52573111 * 7.5,    0.85065081 * 7.5]` = `[0.0, 3.942983325, 6.379881075]`.

**Comment by vedranaa** [comment]
Thanks, @javl. Quite right, all vertices are on the unit sphere (a sphere of radius 1), so you just need to multiply with your desired radius.
